<?php

namespace AppBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UserRepository extends EntityRepository implements UserLoaderInterface{


    public function createFindAllQuery(){
        return $this->_em->createQuery(
            "
            SELECT u.username, u.race
            FROM AppBundle:User u
            "
        );
    }

    public function createFindFriendsQuery($id)
    {
        $query = $this->_em->createQuery(
            "
            SELECT u.friends
            FROM AppBundle:User u
            WHERE u.id = :id
            "
        );

        $query->setParameter('id', $id);

        return $query;
    }

    public function loadUserByUsername($username) {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
